# how to link up the AWS variables they get defined in docker and through the account info when you link up serverless
# also in serverless.yaml

env:
  image_name: my-image #whatever we want to name image
  docker_filepath  : "codebuild/Dockerfile"
  environment_type  : "LINUX_CONTAINER"
  environment_image  : "aws/codebuild/docker:18.09"
  
  # region: us-west-2
  # ecr_repository_uri: <YOUR_ECR_REPOSITORY_URI> #will have to be real repo uri
  #docker tag ${env:image_name}:latest ${env:ecr_repository_uri}


Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-ecr-repository

  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "MyCodeBuildProject"
      BuildSpec: !Sub |
        ${codebuild.buildspec}
      Artifacts:
        Type: "CODEPIPELINE"
      Environment:
        Type: ${env:environment_type}
        Image: ${env:environment_image}
        EnvironmentVariables:
          - Name: "DOCKERFILE_PATH"
            Value: ${env:docker_filepath} # corresponds to path from final yaml template (global bc codefile)
          - Name: ECR_REPOSITORY_URI
            Value: !Join ['', [!Ref MyECRRepository, '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/', !Ref MyECRRepository]]
      ServiceRole: !Ref CodeBuildServiceRole
      # ServiceRole: !GetAtt CodeBuildServiceRole.Arn #from ServiceRole: !Ref CodeBuildServiceRole


#-------
# This YAML file is a CloudFormation template for creating an AWS CodeBuild project. 
# CodeBuild is a fully managed build service that compiles source code, runs tests, and 
# produces software packages that are ready to deploy.

# A build spec is a YAML file that is used to define the build and deployment stages of your CodeBuild project. 
# It specifies the commands that are run during the build process, such as installing dependencies, 
# building and testing your code, and deploying the application.

# In the context of creating an ECR repository along with a Docker image, the build spec file can be used to 
# define the build process for the Docker image. This might include specifying the Dockerfile to use, any dependencies 
# required by the Docker image, and any additional build steps needed to create the image. Once the Docker image is built, 
# the build spec file can also be used to push the image to the ECR repository.

# By defining the build process in a build spec file, you can automate the build and deployment process for your 
# Docker images and ensure that the process is consistent and repeatable.
#-------

# In this file, the env section defines environment variables that can be used in other parts of the file. 
# For example, image_name sets the name of the Docker image that will be built.

# The Resources section defines the CodeBuild project using the AWS::CodeBuild::Project resource type. 
# The Name property sets the name of the project, and the BuildSpec property references a build specification 
# file that defines how to build the Docker image. The Artifacts property specifies the type of artifacts that the project produces,
# and the Environment property specifies the type of environment to use for the build.

# The ServiceRole property references a service role that defines the permissions that the project has to access other AWS resources.
