Resources:
  MyStepFunctionsStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString: !Sub |
        {
          "StartAt": "DownloadDataFromS3",
          "States": {
            "DownloadDataFromS3": {
              "Type": "Task",
              "Resource": "arn:aws:states:::s3:getObject",
              "Next": "ProcessData"
            },
            "ProcessData": {
              "Type": "Task",
              "Resource": {"Fn::GetAtt": ["MyFargateTask", "Arn"]},  # should match the name of the resource defined in the fargate.yml file.
              "Next": "UploadDataToS3"
            },
            "UploadDataToS3": {
              "Type": "Task",
              "Resource": "arn:aws:states:::s3:putObject",
              "End": true
            }
          }
        }

# Resources:: This is the top-level section of the CloudFormation template that defines the AWS resources for the state machine.

# MyStepFunctionsStateMachine: This is the name of the Step Function state machine resource.

# Type: AWS::StepFunctions::StateMachine: This specifies that this resource is a Step Function state machine.

# Properties:: This is the section that specifies the properties of the Step Function state machine.

# DefinitionString: !Sub |: This specifies the JSON definition for the state machine, using a CloudFormation intrinsic function !Sub to substitute variables in the JSON string.

# StartAt: "DownloadDataFromS3": This specifies the starting state of the state machine.

# "DownloadDataFromS3": This is the name of the first state in the state machine.

# "Type": "Task": This specifies that this state is a Task state.

# ---IMPORTANT
# "Resource": "arn:aws:states:::s3:getObject": This specifies the Amazon Resource Name (ARN) of the S3 getObject API that this state executes.

# "Next": "ProcessData": This specifies next step in state machine.

# "ProcessData": This is the name of the second state in the state machine.

# "Resource": {"Fn::GetAtt": ["MyFargateTask", "Arn"]}: This specifies the ARN of the Fargate task that this state executes.

# The MyFargateTask value in the Fn::GetAtt function represents the logical ID of your Fargate task resource, 
# which should match the name of the resource defined in your fargate.yml file.
# the Resource property in the ProcessData state of your Step Function state machine YAML file 
# is referencing a Fargate task that is defined in the fargate.yml file in your my-infrastructure folder.

# "UploadDataToS3": This is the name of the third and final state in the state machine.

# "Resource": "arn:aws:states:::s3:putObject": This specifies the ARN of the S3 putObject API that this state executes.

# Overall the Step Function state machine YAML file defines a simple state machine that downloads data from an S3 bucket, processes the data using a Fargate task, and uploads the processed data back to another S3 bucket.


#--------
# In the DownloadDataFromS3 state, the state machine is downloading data from an S3 bucket, which means you would need to use the getObject API to retrieve the data from the bucket.

# In the UploadDataToS3 state, the state machine is uploading data to an S3 bucket, which means you would need to use the putObject API to store the data in the bucket.

# So in summary, getObject and putObject represent different operations that you can perform on an S3 bucket, depending on whether you want to download or upload data.
