env:
  batch_processing_container : my-batch-processing-container
  batch_processing_image : my-batch-processing-image
  cluster: my-cluster
  
Resources:
  MyFargateTask:
      Type: AWS::ECS::TaskDefinition
      Properties: 
        ContainerDefinitions:
          - Name: ${env:batch_processing_container}    #need to configure the image and container
            Image: ${env:batch_processing_image} 
            Memory: 512
            Cpu: 256

            #important here set environment variables
            Environment:
              - Name: RAW_S3_BUCKET #you will reference these environment variables in your python code
                Value: raw_bucket
              - Name: RAW_S3_OBJECT_KEY
                Value: data_engineer_raw_data.xlsx" # excel file key path

              - Name: TRANSFORMED_S3_BUCKET
                Value: transformed_bucket
              - Name: TRANSFORMED_S3_OBJECT_KEY
                Value: "/" # parquets

  MyFargateService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: !Ref MyFargateTask
      Cluster: ${env:cluster} 
      DesiredCount: 1
      LaunchType: "FARGATE"
