env:
  UserName: 'source-username'
  Password: 'source-username'
  DestUri : 's3://my-bucket/destination-folder' 
  raw_bucket_name : raw_bucket

AWSTemplateFormatVersion: '2010-09-09'


Resources:   #s3 bucket that takes in data sync

  RawS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${env:raw_bucket}  
      
  DataSyncTask:
    Type: 'AWS::DataSync::Task'
    Properties:
      Options:
        VerifyMode: ONLY_FILES_TRANSFERRED
        OverwriteMode: NEWER_FILES_ARE_IGNORED #need to change this parameter
        TaskQueueing: ENABLED
        LogLevel: OFF
        TransferOptions:
          PreserveDeletedFiles: ENABLED
          PreserveAttributes: ENABLED
          VerifyMode: ONLY_FILES_TRANSFERRED
      Sources:
        - Uri: 'smb://source-server/source-folder'
          Credentials:
            UserName: ${env:UserName}
            Password: ${env:Password}
      Destinations:
        - Uri:  ${env:DestUri} # ok so heres the destination 
          S3Config:
            BucketAccessRoleArn: !GetAtt S3Bucket.Arn

  RawS3BucketEvent:
    Type: AWS::S3::BucketEvent
    Properties:
      Bucket: !Ref  ${env:raw_bucket}
      Events:
        - s3:ObjectCreated:Put
      NotificationConfiguration:
        StepFunctionsConfigurations:
        - StateMachineArn: !GetAtt MyStepFunctionsStateMachine.Arn



# i need this to reference aws s3
# this one needs a lot of revamp !!
#because i want it to  be able to update!!
# maybe newer files arent ignored 
# and each row should have metadata i think like added or edited !
# or else i need to reload parquet file