env:
  crawler_name: transformed-crawler #whatever we want to name image
  transformed_bucket: transformed_bucket
  database_name: mydatabase
  transformed_bucket_path: s3://transformed_bucket


Resources:
  TransformedS3Bucket: #bucket  to crawl
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${env:transformed_bucket}


  MyGlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: ${env:crawler_name}
      Role: MyGlueCrawlerRole
      DatabaseName: ${env:database_name}
      Targets:
        S3Targets:
        - Path: ${env:transformed_bucket_path}
      SchemaChangeDetectionPolicy:
        PolicyInclude: all

