Resources:
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: {}

  MyVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVpc
      InternetGatewayId: !Ref MyInternetGateway

Outputs:
  MyInternetGatewayId:
    Value: !Ref MyInternetGateway
    Export:
      Name: MyInternetGatewayId

# This YAML file creates an Internet Gateway resource in AWS CloudFormation using the AWS::EC2::InternetGateway resource type. 

# An Internet Gateway is a horizontally scalable, redundant, and highly available VPC component that allows communication 
# between instances in your VPC and the internet.

# The Internet Gateway resource is created with a logical ID of "MyInternetGateway", and it has no properties defined, so it is
# made with the default settings.

# The output section of the file exports the logical ID of the Internet Gateway as a named export, so it can be referenced in 
# other templates or stacks. The output value is the Amazon Resource Name (ARN) of the Internet Gateway resource.

# Overall, this YAML file can be used to easily create an Internet Gateway resource that can be used to provide access 
# to and from your VPC.

#--------ROUTE TABLE
# An Internet Gateway (IGW) is used to allow resources within your VPC to access the internet, or to allow the internet to access resources within 
# your VPC. In order to enable access to the internet, an IGW must be attached to a VPC.

# An IGW cannot be directly attached to any other resources, only to a VPC. However, once an IGW is attached to a VPC, you can set up routing 
# to direct traffic to and from the internet through the IGW.

# For example, you can create a route table and configure the routes to direct traffic to the IGW. You can associate the route table with one
# or more subnets in your VPC. When a resource in the subnet sends traffic to the internet, the route table will direct 
# that traffic to the IGW.
