env:
  my_bucket : my_bucket
  
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket
      
  MyGlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          StringEquals:
            aws:SourceArn: arn:aws:glue:us-west-2:account-id:crawler/my-crawler
      Path: /
      Policies:
        - PolicyName: GlueCrawlerS3Access # this is inline
          PolicyDocument:
            Version: "2012-10-17"

            Statement:
              StringLike:
                s3:prefix: s3://${env:my_bucket}/*

            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:GetObjectAcl
            Resource: "*"
  MyGlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: my-crawler
      Role: !Ref MyGlueCrawlerRole
      DatabaseName: mydatabase
      Targets:
        S3Targets:
        - Path: s3://${env:my_bucket}
      SchemaChangeDetectionPolicy:
        PolicyInclude: all
