
env:
  version : '2012-10-17'

Resources:
  MyS3AccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'MyS3AccessRole'
      AssumeRolePolicyDocument:
        Version: ${env:version}
        Statement:
          StringEquals:
            sts:ExternalId: !Ref "AWS::AccountId"
      Policies:
        - PolicyName: 'MyS3AccessPolicy' # this is inline
          PolicyDocument:
            Version: ${env:version}
            Statement:
              StringEquals:
                sts:ExternalId: !Ref "AWS::AccountId"

